/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class InscripcionUI extends javax.swing.JFrame {

    /**
     * Creates new form InscripcionUI
     */
    public InscripcionUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellidoTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        atletismoChck = new javax.swing.JCheckBox();
        natacionChck = new javax.swing.JCheckBox();
        ciclismoChck = new javax.swing.JCheckBox();
        pesasChck = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        menor18 = new javax.swing.JRadioButton();
        entre18y40 = new javax.swing.JRadioButton();
        mayor40 = new javax.swing.JRadioButton();
        agregarBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableParticipantes = new javax.swing.JTable();
        Jpequenia = new javax.swing.JRadioButton();
        jGrande = new javax.swing.JRadioButton();
        jMediana = new javax.swing.JRadioButton();
        jExtra = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de  Inscripcion");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        nombreTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Apellido");

        apellidoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Edad");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Disciplina");

        atletismoChck.setText("Atletismo");

        natacionChck.setText("Natacion");
        natacionChck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                natacionChckActionPerformed(evt);
            }
        });

        ciclismoChck.setText("Ciclismo");

        pesasChck.setText("Levantamiento de pesas");

        jLabel6.setText("Talla Camisa");

        menor18.setText(" menores de 18 años");

        entre18y40.setMnemonic('1');
        entre18y40.setText("18 a 40 años");

        mayor40.setText("mayores de 40");

        agregarBtn.setText("agregar");

        salirBtn.setText("salir");

        tableParticipantes.setAutoCreateRowSorter(true);
        tableParticipantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Categoria", "Talla", "Disciplina"
            }
        ));
        jScrollPane2.setViewportView(tableParticipantes);

        Jpequenia.setText("Pequeña");

        jGrande.setText("Grande");

        jMediana.setText("Mediana");

        jExtra.setText("Extra Grande");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(menor18)
                                        .addGap(18, 18, 18)
                                        .addComponent(entre18y40))
                                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(atletismoChck)
                                    .addComponent(Jpequenia))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMediana)
                                    .addComponent(natacionChck))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ciclismoChck)
                                        .addGap(18, 18, 18)
                                        .addComponent(pesasChck))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jGrande)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mayor40)
                                            .addComponent(jExtra)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(salirBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(menor18)
                    .addComponent(entre18y40)
                    .addComponent(mayor40))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Jpequenia)
                    .addComponent(jGrande)
                    .addComponent(jMediana)
                    .addComponent(jExtra))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(atletismoChck, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(natacionChck)
                    .addComponent(ciclismoChck)
                    .addComponent(pesasChck))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarBtn)
                    .addComponent(salirBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void natacionChckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_natacionChckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_natacionChckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscripcionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscripcionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscripcionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscripcionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscripcionUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Jpequenia;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JCheckBox atletismoChck;
    private javax.swing.JCheckBox ciclismoChck;
    private javax.swing.JRadioButton entre18y40;
    private javax.swing.JRadioButton jExtra;
    private javax.swing.JRadioButton jGrande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jMediana;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton mayor40;
    private javax.swing.JRadioButton menor18;
    private javax.swing.JCheckBox natacionChck;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JCheckBox pesasChck;
    private javax.swing.JButton salirBtn;
    private javax.swing.JTable tableParticipantes;
    // End of variables declaration//GEN-END:variables

    public JRadioButton getJpequenia() {
        return Jpequenia;
    }

    public void setJpequenia(JRadioButton Jpequenia) {
        this.Jpequenia = Jpequenia;
    }

    public JButton getAgregarBtn() {
        return agregarBtn;
    }

    public void setAgregarBtn(JButton agregarBtn) {
        this.agregarBtn = agregarBtn;
    }

    public JCheckBox getAtletismoChck() {
        return atletismoChck;
    }

    public void setAtletismoChck(JCheckBox atletismoChck) {
        this.atletismoChck = atletismoChck;
    }

    public JCheckBox getCiclismoChck() {
        return ciclismoChck;
    }

    public void setCiclismoChck(JCheckBox ciclismoChck) {
        this.ciclismoChck = ciclismoChck;
    }

    public JRadioButton getjExtra() {
        return jExtra;
    }

    public void setjExtra(JRadioButton jExtra) {
        this.jExtra = jExtra;
    }

    public JRadioButton getjGrande() {
        return jGrande;
    }

    public void setjGrande(JRadioButton jGrande) {
        this.jGrande = jGrande;
    }

    public JRadioButton getjMediana() {
        return jMediana;
    }

    public void setjMediana(JRadioButton jMediana) {
        this.jMediana = jMediana;
    }

    

    public JCheckBox getNatacionChck() {
        return natacionChck;
    }

    public void setNatacionChck(JCheckBox natacionChck) {
        this.natacionChck = natacionChck;
    }

    public JTextField getNombreTxt() {
        return nombreTxt;
    }

    public void setNombreTxt(JTextField nombreTxt) {
        this.nombreTxt = nombreTxt;
    }

    public JCheckBox getPesasChck() {
        return pesasChck;
    }

    public void setPesasChck(JCheckBox pesasChck) {
        this.pesasChck = pesasChck;
    }

    public JButton getSalirBtn() {
        return salirBtn;
    }

    public void setSalirBtn(JButton salirBtn) {
        this.salirBtn = salirBtn;
    }

    public JTable getTableParticipantes() {
        return tableParticipantes;
    }

    public void setTableParticipantes(JTable tableParticipantes) {
        this.tableParticipantes = tableParticipantes;
    }

    public JTextField getApellidoTxt() {
        return apellidoTxt;
    }

    public void setApellidoTxt(JTextField apellidoTxt) {
        this.apellidoTxt = apellidoTxt;
    }

    public JRadioButton getEntre18y40() {
        return entre18y40;
    }

    public void setEntre18y40(JRadioButton entre18y40) {
        this.entre18y40 = entre18y40;
    }

    public JRadioButton getMayor40() {
        return mayor40;
    }

    public void setMayor40(JRadioButton mayor40) {
        this.mayor40 = mayor40;
    }

    public JRadioButton getMenor18() {
        return menor18;
    }

    public void setMenor18(JRadioButton menor18) {
        this.menor18 = menor18;
    }

 


}
